# MySQL. Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
# gem install mysql
# On Mac OS X:
# sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
# sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
# This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
# gem install mysql
# Choose the win32 build.
# Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
# http://dev.mysql.com/doc/refman/5.0/en/old-client.html

<%
  # http://mislav.uniqpath.com/rails/branching-the-database-along-with-your-code/
  # if want to create specific db for branch => git config --bool branch.#{branch}.database true
  branch = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '')
  suffix = `git config --bool branch.#{branch}.database`.chomp == 'true' ? "_#{branch}" : ""
%>

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  # ... adapter/auth config ...
  database: utf8_translatable<%= suffix %>_development
  pool: 5
  username: root
  password:
  host: 127.0.0.1
  timeout: 5000

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  # ... adapter/auth config ...
  database: utf8_translatable<%= suffix %>_testing
  pool: 5
  username: root
  password:
  host: 127.0.0.1
  timeout: 5000

cucumber:
  <<: *test

production: &production
  adapter: mysql2
  encoding: utf8
  reconnect: false
  # ... adapter/auth config ...
  database: utf8_translatable<%= suffix %>_development
  pool: 5
  username: root
  password:
  host: 127.0.0.1
  timeout: 5000
  
staging:
  <<: *production